var annotated_dup =
[
    [ "Button", "class_button.html", "class_button" ],
    [ "Enemy", "class_enemy.html", "class_enemy" ],
    [ "EnemyMissile", "class_enemy_missile.html", "class_enemy_missile" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "FireballMissile", "class_fireball_missile.html", "class_fireball_missile" ],
    [ "FireballSpell", "class_fireball_spell.html", "class_fireball_spell" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameOverScene", "class_game_over_scene.html", "class_game_over_scene" ],
    [ "Level1", "class_level1.html", "class_level1" ],
    [ "MenuScene", "class_menu_scene.html", "class_menu_scene" ],
    [ "Missile", "class_missile.html", "class_missile" ],
    [ "Obstacle", "class_obstacle.html", "class_obstacle" ],
    [ "OverworldMap", "class_overworld_map.html", null ],
    [ "ParticleMissile", "class_particle_missile.html", "class_particle_missile" ],
    [ "ParticleSpell", "class_particle_spell.html", "class_particle_spell" ],
    [ "PauseScene", "class_pause_scene.html", "class_pause_scene" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerGUI", "class_player_g_u_i.html", "class_player_g_u_i" ],
    [ "PlotScene", "class_plot_scene.html", "class_plot_scene" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "SceneManager", "class_scene_manager.html", "class_scene_manager" ],
    [ "Spell", "class_spell.html", "class_spell" ],
    [ "TextButton", "class_text_button.html", "class_text_button" ],
    [ "TileMap", "class_tile_map.html", "class_tile_map" ],
    [ "Tree", "class_tree.html", "class_tree" ],
    [ "UIClose", "class_u_i_close.html", "class_u_i_close" ],
    [ "UIClosePause", "class_u_i_close_pause.html", "class_u_i_close_pause" ],
    [ "UICommand", "class_u_i_command.html", "class_u_i_command" ],
    [ "UIGotoMenu", "class_u_i_goto_menu.html", "class_u_i_goto_menu" ],
    [ "UINextScene", "class_u_i_next_scene.html", "class_u_i_next_scene" ],
    [ "UIRepeatLevel", "class_u_i_repeat_level.html", "class_u_i_repeat_level" ],
    [ "Utils", "class_utils.html", null ],
    [ "Wraith", "class_wraith.html", "class_wraith" ]
];